[package]
name = "bin"
version = "0.1.0"
edition = "2021"

[dependencies]
zerotierone-controller = { path = "../crates/zerotierone-controller" }
clap = { version = "4.5.1", features = ["cargo"] }
tokio = { version = "1.36.0", features = ["rt-multi-thread", "macros"] }
anyhow = "1.0.80"
